import { Commander } from "../models/Commander";
import { EnumHouse } from "../enums/EnumHouse";

export const CommanderDefinitions = [
    new Commander({id:1, commander: "name1", strength: 0, houseName: EnumHouse.BARATHEON, used: false }),
    new Commander({id:2, commander: "name2", strength: 1, houseName: EnumHouse.BARATHEON, used: false }),
    new Commander({id:3, commander: "name3", strength: 1, houseName: EnumHouse.BARATHEON, used: false }),
    new Commander({id:4, commander: "name4", strength: 2, houseName: EnumHouse.BARATHEON, used: false }),
    new Commander({id:5, commander: "name5", strength: 2, houseName: EnumHouse.BARATHEON, used: false }),
    new Commander({id:6, commander: "name6", strength: 3, houseName: EnumHouse.BARATHEON, used: false }),
    new Commander({id:7, commander: "name7", strength: 4, houseName: EnumHouse.BARATHEON, used: false }),

    new Commander({id:1, commander: "name1", strength: 0, houseName: EnumHouse.LANNISTER, used: false }),
    new Commander({id:2, commander: "name2", strength: 1, houseName: EnumHouse.LANNISTER, used: false }),
    new Commander({id:3, commander: "name3", strength: 1, houseName: EnumHouse.LANNISTER, used: false }),
    new Commander({id:4, commander: "name4", strength: 2, houseName: EnumHouse.LANNISTER, used: false }),
    new Commander({id:5, commander: "name5", strength: 2, houseName: EnumHouse.LANNISTER, used: false }),
    new Commander({id:6, commander: "name6", strength: 3, houseName: EnumHouse.LANNISTER, used: false }),
    new Commander({id:7, commander: "name7", strength: 4, houseName: EnumHouse.LANNISTER, used: false }),
    

    new Commander({id:1, commander: "name1", strength: 0, houseName: EnumHouse.ARRYN, used: false}),
    new Commander({id:2, commander: "name2", strength: 1, houseName: EnumHouse.ARRYN, used: false}),
    new Commander({id:3, commander: "name3", strength: 1, houseName: EnumHouse.ARRYN, used: false}),
    new Commander({id:4, commander: "name4", strength: 2, houseName: EnumHouse.ARRYN, used: false}),
    new Commander({id:5, commander: "name5", strength: 2, houseName: EnumHouse.ARRYN, used: false}),
    new Commander({id:6, commander: "name6", strength: 3, houseName: EnumHouse.ARRYN, used: false}),
    new Commander({id:7, commander: "name7", strength: 4, houseName: EnumHouse.ARRYN, used: false}),

    new Commander({id:1, commander: "name1", strength: 0, houseName: EnumHouse.TARGARYEN, used: false}),
    new Commander({id:2, commander: "name2", strength: 1, houseName: EnumHouse.TARGARYEN, used: false}),
    new Commander({id:3, commander: "name3", strength: 1, houseName: EnumHouse.TARGARYEN, used: false}),
    new Commander({id:4, commander: "name4", strength: 2, houseName: EnumHouse.TARGARYEN, used: false}),
    new Commander({id:5, commander: "name5", strength: 2, houseName: EnumHouse.TARGARYEN, used: false}),
    new Commander({id:6, commander: "name6", strength: 3, houseName: EnumHouse.TARGARYEN, used: false}),
    new Commander({id:7, commander: "name7", strength: 4, houseName: EnumHouse.TARGARYEN, used: false}),
    
    new Commander({id:1, commander: "name1", strength: 0, houseName: EnumHouse.TULLY, used: false}),
    new Commander({id:2, commander: "name2", strength: 1, houseName: EnumHouse.TULLY, used: false}),
    new Commander({id:3, commander: "name3", strength: 1, houseName: EnumHouse.TULLY, used: false}),
    new Commander({id:4, commander: "name4", strength: 2, houseName: EnumHouse.TULLY, used: false}),
    new Commander({id:5, commander: "name5", strength: 2, houseName: EnumHouse.TULLY, used: false}),
    new Commander({id:6, commander: "name6", strength: 3, houseName: EnumHouse.TULLY, used: false}),
    new Commander({id:7, commander: "name7", strength: 4, houseName: EnumHouse.TULLY, used: false}),

    new Commander({id:1, commander: "name1", strength: 0, houseName: EnumHouse.TYLLER, used: false}),
    new Commander({id:2, commander: "name2", strength: 1, houseName: EnumHouse.TYLLER, used: false}),
    new Commander({id:3, commander: "name3", strength: 1, houseName: EnumHouse.TYLLER, used: false}),
    new Commander({id:4, commander: "name4", strength: 2, houseName: EnumHouse.TYLLER, used: false}),
    new Commander({id:5, commander: "name5", strength: 2, houseName: EnumHouse.TYLLER, used: false}),
    new Commander({id:6, commander: "name6", strength: 3, houseName: EnumHouse.TYLLER, used: false}),
    new Commander({id:7, commander: "name7", strength: 4, houseName: EnumHouse.TYLLER, used: false}),

    new Commander({id:1, commander: "name1", strength: 0, houseName: EnumHouse.STARK, used: false}),
    new Commander({id:2, commander: "name2", strength: 1, houseName: EnumHouse.STARK, used: false}),
    new Commander({id:3, commander: "name3", strength: 1, houseName: EnumHouse.STARK, used: false}),
    new Commander({id:4, commander: "name4", strength: 2, houseName: EnumHouse.STARK, used: false}),
    new Commander({id:5, commander: "name5", strength: 2, houseName: EnumHouse.STARK, used: false}),
    new Commander({id:6, commander: "name6", strength: 3, houseName: EnumHouse.STARK, used: false}),
    new Commander({id:7, commander: "name7", strength: 4, houseName: EnumHouse.STARK, used: false}),

    new Commander({id:1, commander: "name1", strength: 0, houseName: EnumHouse.GREYJOY, used: false}),
    new Commander({id:2, commander: "name2", strength: 1, houseName: EnumHouse.GREYJOY, used: false}),
    new Commander({id:3, commander: "name3", strength: 1, houseName: EnumHouse.GREYJOY, used: false}),
    new Commander({id:4, commander: "name4", strength: 2, houseName: EnumHouse.GREYJOY, used: false}),
    new Commander({id:5, commander: "name5", strength: 2, houseName: EnumHouse.GREYJOY, used: false}),
    new Commander({id:6, commander: "name6", strength: 3, houseName: EnumHouse.GREYJOY, used: false}),
    new Commander({id:7, commander: "name7", strength: 4, houseName: EnumHouse.GREYJOY, used: false}),

    new Commander({id:1, commander: "name1", strength: 0, houseName: EnumHouse.MARTELL, used: false}),
    new Commander({id:2, commander: "name2", strength: 1, houseName: EnumHouse.MARTELL, used: false}),
    new Commander({id:3, commander: "name3", strength: 1, houseName: EnumHouse.MARTELL, used: false}),
    new Commander({id:4, commander: "name4", strength: 2, houseName: EnumHouse.MARTELL, used: false}),
    new Commander({id:5, commander: "name5", strength: 2, houseName: EnumHouse.MARTELL, used: false}),
    new Commander({id:6, commander: "name6", strength: 3, houseName: EnumHouse.MARTELL, used: false}),
    new Commander({id:7, commander: "name7", strength: 4, houseName: EnumHouse.MARTELL, used: false}),
]