import { Commander } from "../models/Commander";
import { EnumHouse } from "../enums/EnumHouse";

export const CommanderDefinitions = [
    new Commander({id:1, commander: "../assets/Commanders/BARATHEON/BARATHEON0.png", strength: 0, houseName: EnumHouse.BARATHEON, used: true }),
    new Commander({id:2, commander: "../assets/Commanders/BARATHEON/BARATHEON1.png", strength: 1, houseName: EnumHouse.BARATHEON, used: false }),
    new Commander({id:3, commander: "../assets/Commanders/BARATHEON/BARATHEON2.png", strength: 1, houseName: EnumHouse.BARATHEON, used: false }),
    new Commander({id:4, commander: "../assets/Commanders/BARATHEON/BARATHEON3.png", strength: 2, houseName: EnumHouse.BARATHEON, used: false }),
    new Commander({id:5, commander: "../assets/Commanders/BARATHEON/BARATHEON4.png", strength: 2, houseName: EnumHouse.BARATHEON, used: false }),
    new Commander({id:6, commander: "../assets/Commanders/BARATHEON/BARATHEON5.png", strength: 3, houseName: EnumHouse.BARATHEON, used: true }),
    new Commander({id:7, commander: "../assets/Commanders/BARATHEON/BARATHEON6.png", strength: 4, houseName: EnumHouse.BARATHEON, used: false }),

    new Commander({id:1, commander: "../assets/Commanders/LANNISTER/LANNISTER0.png", strength: 0, houseName: EnumHouse.LANNISTER, used: false }),
    new Commander({id:2, commander: "../assets/Commanders/LANNISTER/LANNISTER1.png", strength: 1, houseName: EnumHouse.LANNISTER, used: false }),
    new Commander({id:3, commander: "../assets/Commanders/LANNISTER/LANNISTER2.png", strength: 1, houseName: EnumHouse.LANNISTER, used: false }),
    new Commander({id:4, commander: "../assets/Commanders/LANNISTER/LANNISTER3.png", strength: 2, houseName: EnumHouse.LANNISTER, used: false }),
    new Commander({id:5, commander: "../assets/Commanders/LANNISTER/LANNISTER4.png", strength: 2, houseName: EnumHouse.LANNISTER, used: false }),
    new Commander({id:6, commander: "../assets/Commanders/LANNISTER/LANNISTER5.png", strength: 3, houseName: EnumHouse.LANNISTER, used: false }),
    new Commander({id:7, commander: "../assets/Commanders/LANNISTER/LANNISTER6.png", strength: 4, houseName: EnumHouse.LANNISTER, used: false }),
    

    new Commander({id:1, commander: "../assets/Commanders/ARRYN/ARRYN0.png", strength: 0, houseName: EnumHouse.ARRYN, used: false}),
    new Commander({id:2, commander: "../assets/Commanders/ARRYN/ARRYN1.png", strength: 1, houseName: EnumHouse.ARRYN, used: false}),
    new Commander({id:3, commander: "../assets/Commanders/ARRYN/ARRYN2.png", strength: 1, houseName: EnumHouse.ARRYN, used: false}),
    new Commander({id:4, commander: "../assets/Commanders/ARRYN/ARRYN3.png", strength: 2, houseName: EnumHouse.ARRYN, used: false}),
    new Commander({id:5, commander: "../assets/Commanders/ARRYN/ARRYN4.png", strength: 2, houseName: EnumHouse.ARRYN, used: false}),
    new Commander({id:6, commander: "../assets/Commanders/ARRYN/ARRYN5.png", strength: 3, houseName: EnumHouse.ARRYN, used: false}),
    new Commander({id:7, commander: "../assets/Commanders/ARRYN/ARRYN6.png", strength: 4, houseName: EnumHouse.ARRYN, used: false}),

    new Commander({id:1, commander: "../assets/Commanders/TARGARYEN/TARGARYEN0.png", strength: 0, houseName: EnumHouse.TARGARYEN, used: false}),
    new Commander({id:2, commander: "../assets/Commanders/TARGARYEN/TARGARYEN1.png", strength: 1, houseName: EnumHouse.TARGARYEN, used: false}),
    new Commander({id:3, commander: "../assets/Commanders/TARGARYEN/TARGARYEN2.png", strength: 1, houseName: EnumHouse.TARGARYEN, used: false}),
    new Commander({id:4, commander: "../assets/Commanders/TARGARYEN/TARGARYEN3.png", strength: 2, houseName: EnumHouse.TARGARYEN, used: false}),
    new Commander({id:5, commander: "../assets/Commanders/TARGARYEN/TARGARYEN4.png", strength: 2, houseName: EnumHouse.TARGARYEN, used: false}),
    new Commander({id:6, commander: "../assets/Commanders/TARGARYEN/TARGARYEN5.png", strength: 3, houseName: EnumHouse.TARGARYEN, used: false}),
    new Commander({id:7, commander: "../assets/Commanders/TARGARYEN/TARGARYEN6.png", strength: 4, houseName: EnumHouse.TARGARYEN, used: false}),
    
    new Commander({id:1, commander: "../assets/Commanders/TULLY/TULLY0.png", strength: 0, houseName: EnumHouse.TULLY, used: false}),
    new Commander({id:2, commander: "../assets/Commanders/TULLY/TULLY1.png", strength: 1, houseName: EnumHouse.TULLY, used: false}),
    new Commander({id:3, commander: "../assets/Commanders/TULLY/TULLY2.png", strength: 1, houseName: EnumHouse.TULLY, used: false}),
    new Commander({id:4, commander: "../assets/Commanders/TULLY/TULLY3.png", strength: 2, houseName: EnumHouse.TULLY, used: false}),
    new Commander({id:5, commander: "../assets/Commanders/TULLY/TULLY4.png", strength: 2, houseName: EnumHouse.TULLY, used: false}),
    new Commander({id:6, commander: "../assets/Commanders/TULLY/TULLY5.png", strength: 3, houseName: EnumHouse.TULLY, used: false}),
    new Commander({id:7, commander: "../assets/Commanders/TULLY/TULLY6.png", strength: 4, houseName: EnumHouse.TULLY, used: false}),

    new Commander({id:1, commander: "../assets/Commanders/TYLLER/TYLLER0.png", strength: 0, houseName: EnumHouse.TYLLER, used: false}),
    new Commander({id:2, commander: "../assets/Commanders/TYLLER/TYLLER1.png", strength: 1, houseName: EnumHouse.TYLLER, used: false}),
    new Commander({id:3, commander: "../assets/Commanders/TYLLER/TYLLER2.png", strength: 1, houseName: EnumHouse.TYLLER, used: false}),
    new Commander({id:4, commander: "../assets/Commanders/TYLLER/TYLLER3.png", strength: 2, houseName: EnumHouse.TYLLER, used: false}),
    new Commander({id:5, commander: "../assets/Commanders/TYLLER/TYLLER4.png", strength: 2, houseName: EnumHouse.TYLLER, used: false}),
    new Commander({id:6, commander: "../assets/Commanders/TYLLER/TYLLER5.png", strength: 3, houseName: EnumHouse.TYLLER, used: false}),
    new Commander({id:7, commander: "../assets/Commanders/TYLLER/TYLLER6.png", strength: 4, houseName: EnumHouse.TYLLER, used: false}),

    new Commander({id:1, commander: "../assets/Commanders/STARK/STARK0.png", strength: 0, houseName: EnumHouse.STARK, used: false}),
    new Commander({id:2, commander: "../assets/Commanders/STARK/STARK1.png", strength: 1, houseName: EnumHouse.STARK, used: false}),
    new Commander({id:3, commander: "../assets/Commanders/STARK/STARK2.png", strength: 1, houseName: EnumHouse.STARK, used: false}),
    new Commander({id:4, commander: "../assets/Commanders/STARK/STARK3.png", strength: 2, houseName: EnumHouse.STARK, used: false}),
    new Commander({id:5, commander: "../assets/Commanders/STARK/STARK4.png", strength: 2, houseName: EnumHouse.STARK, used: false}),
    new Commander({id:6, commander: "../assets/Commanders/STARK/STARK5.png", strength: 3, houseName: EnumHouse.STARK, used: false}),
    new Commander({id:7, commander: "../assets/Commanders/STARK/STARK6.png", strength: 4, houseName: EnumHouse.STARK, used: false}),

    new Commander({id:1, commander: "../assets/Commanders/GREYJOY/GREYJOY0.png", strength: 0, houseName: EnumHouse.GREYJOY, used: false}),
    new Commander({id:2, commander: "../assets/Commanders/GREYJOY/GREYJOY1.png", strength: 1, houseName: EnumHouse.GREYJOY, used: false}),
    new Commander({id:3, commander: "../assets/Commanders/GREYJOY/GREYJOY2.png", strength: 1, houseName: EnumHouse.GREYJOY, used: false}),
    new Commander({id:4, commander: "../assets/Commanders/GREYJOY/GREYJOY3.png", strength: 2, houseName: EnumHouse.GREYJOY, used: false}),
    new Commander({id:5, commander: "../assets/Commanders/GREYJOY/GREYJOY4.png", strength: 2, houseName: EnumHouse.GREYJOY, used: false}),
    new Commander({id:6, commander: "../assets/Commanders/GREYJOY/GREYJOY5.png", strength: 3, houseName: EnumHouse.GREYJOY, used: false}),
    new Commander({id:7, commander: "../assets/Commanders/GREYJOY/GREYJOY6.png", strength: 4, houseName: EnumHouse.GREYJOY, used: false}),

    new Commander({id:1, commander: "../assets/Commanders/MARTELL/MARTELL0.png", strength: 0, houseName: EnumHouse.MARTELL, used: false}),
    new Commander({id:2, commander: "../assets/Commanders/MARTELL/MARTELL1.png", strength: 1, houseName: EnumHouse.MARTELL, used: false}),
    new Commander({id:3, commander: "../assets/Commanders/MARTELL/MARTELL2.png", strength: 1, houseName: EnumHouse.MARTELL, used: false}),
    new Commander({id:4, commander: "../assets/Commanders/MARTELL/MARTELL3.png", strength: 2, houseName: EnumHouse.MARTELL, used: false}),
    new Commander({id:5, commander: "../assets/Commanders/MARTELL/MARTELL4.png", strength: 2, houseName: EnumHouse.MARTELL, used: false}),
    new Commander({id:6, commander: "../assets/Commanders/MARTELL/MARTELL5.png", strength: 3, houseName: EnumHouse.MARTELL, used: false}),
    new Commander({id:7, commander: "../assets/Commanders/MARTELL/MARTELL6.png", strength: 4, houseName: EnumHouse.MARTELL, used: false}),
]