import { EnumHouse } from "../enums/EnumHouse"
import {Order} from "../models/Order"


export const OrderDefinitons = [
    new Order({id:1,order: "attack+1",special: true, houseName: EnumHouse.LANNISTER}),
    new Order({id:2,order: "attack0",special: false, houseName: EnumHouse.LANNISTER}),
    new Order({id:3,order: "attack-1",special: false, houseName: EnumHouse.LANNISTER}),
    new Order({id:4,order: "defend+2",special: true, houseName: EnumHouse.LANNISTER}),
    new Order({id:5,order: "defend+1",special: false, houseName: EnumHouse.LANNISTER }),
    new Order({id:6,order: "defend+1",special: false, houseName: EnumHouse.LANNISTER}),
    new Order({id:7,order: "pillage+",special: true, houseName: EnumHouse.LANNISTER}),
    new Order({id:8,order: "pillage",special: false, houseName: EnumHouse.LANNISTER}),
    new Order({id:9,order: "pillage",special: false, houseName: EnumHouse.LANNISTER}),
    new Order({id:10,order: "support+1",special: true, houseName: EnumHouse.LANNISTER}),
    new Order({id:11,order: "support",special: false, houseName: EnumHouse.LANNISTER}),
    new Order({id:12,order: "support",special: false, houseName: EnumHouse.LANNISTER}),
    new Order({id:13,order: "power+",special: true, houseName: EnumHouse.LANNISTER}),
    new Order({id:14,order: "power",special: false, houseName: EnumHouse.LANNISTER}),
    new Order({id:15,order: "power",special: false, houseName: EnumHouse.LANNISTER }),
    
    new Order({id:1,order: "attack+1",special: true, houseName: EnumHouse.BARATHEON}),
    new Order({id:2,order: "attack0",special: false, houseName: EnumHouse.BARATHEON}),
    new Order({id:3,order: "attack-1",special: false, houseName: EnumHouse.BARATHEON}),
    new Order({id:4,order: "defend+2",special: true, houseName: EnumHouse.BARATHEON}),
    new Order({id:5,order: "defend+1",special: false, houseName: EnumHouse.BARATHEON }),
    new Order({id:6,order: "defend+1",special: false, houseName: EnumHouse.BARATHEON}),
    new Order({id:7,order: "pillage+",special: true, houseName: EnumHouse.BARATHEON}),
    new Order({id:8,order: "pillage",special: false, houseName: EnumHouse.BARATHEON}),
    new Order({id:9,order: "pillage",special: false, houseName: EnumHouse.BARATHEON}),
    new Order({id:10,order: "support+1",special: true, houseName: EnumHouse.BARATHEON}),
    new Order({id:11,order: "support",special: false, houseName: EnumHouse.BARATHEON}),
    new Order({id:12,order: "support",special: false, houseName: EnumHouse.BARATHEON}),
    new Order({id:13,order: "power+",special: true, houseName: EnumHouse.BARATHEON}),
    new Order({id:14,order: "power",special: false, houseName: EnumHouse.BARATHEON}),
    new Order({id:15,order: "power",special: false, houseName: EnumHouse.BARATHEON }),

    new Order({id:1,order: "attack+1",special: true, houseName: EnumHouse.ARRYN}),
    new Order({id:2,order: "attack0",special: false, houseName: EnumHouse.ARRYN}),
    new Order({id:3,order: "attack-1",special: false, houseName: EnumHouse.ARRYN}),
    new Order({id:4,order: "defend+2",special: true, houseName: EnumHouse.ARRYN}),
    new Order({id:5,order: "defend+1",special: false, houseName: EnumHouse.ARRYN }),
    new Order({id:6,order: "defend+1",special: false, houseName: EnumHouse.ARRYN}),
    new Order({id:7,order: "pillage+",special: true, houseName: EnumHouse.ARRYN}),
    new Order({id:8,order: "pillage",special: false, houseName: EnumHouse.ARRYN}),
    new Order({id:9,order: "pillage",special: false, houseName: EnumHouse.ARRYN}),
    new Order({id:10,order: "support+1",special: true, houseName: EnumHouse.ARRYN}),
    new Order({id:11,order: "support",special: false, houseName: EnumHouse.ARRYN}),
    new Order({id:12,order: "support",special: false, houseName: EnumHouse.ARRYN}),
    new Order({id:13,order: "power+",special: true, houseName: EnumHouse.ARRYN}),
    new Order({id:14,order: "power",special: false, houseName: EnumHouse.ARRYN}),
    new Order({id:15,order: "power",special: false, houseName: EnumHouse.ARRYN }),

    new Order({id:1,order: "attack+1",special: true, houseName: EnumHouse.TULLY}),
    new Order({id:2,order: "attack0",special: false, houseName: EnumHouse.TULLY}),
    new Order({id:3,order: "attack-1",special: false, houseName: EnumHouse.TULLY}),
    new Order({id:4,order: "defend+2",special: true, houseName: EnumHouse.TULLY}),
    new Order({id:5,order: "defend+1",special: false, houseName: EnumHouse.TULLY }),
    new Order({id:6,order: "defend+1",special: false, houseName: EnumHouse.TULLY}),
    new Order({id:7,order: "pillage+",special: true, houseName: EnumHouse.TULLY}),
    new Order({id:8,order: "pillage",special: false, houseName: EnumHouse.TULLY}),
    new Order({id:9,order: "pillage",special: false, houseName: EnumHouse.TULLY}),
    new Order({id:10,order: "support+1",special: true, houseName: EnumHouse.TULLY}),
    new Order({id:11,order: "support",special: false, houseName: EnumHouse.TULLY}),
    new Order({id:12,order: "support",special: false, houseName: EnumHouse.TULLY}),
    new Order({id:13,order: "power+",special: true, houseName: EnumHouse.TULLY}),
    new Order({id:14,order: "power",special: false, houseName: EnumHouse.TULLY}),
    new Order({id:15,order: "power",special: false, houseName: EnumHouse.TULLY }),

    new Order({id:1,order: "attack+1",special: true, houseName: EnumHouse.TARGARYEN}),
    new Order({id:2,order: "attack0",special: false, houseName: EnumHouse.TARGARYEN}),
    new Order({id:3,order: "attack-1",special: false, houseName: EnumHouse.TARGARYEN}),
    new Order({id:4,order: "defend+2",special: true, houseName: EnumHouse.TARGARYEN}),
    new Order({id:5,order: "defend+1",special: false, houseName: EnumHouse.TARGARYEN }),
    new Order({id:6,order: "defend+1",special: false, houseName: EnumHouse.TARGARYEN}),
    new Order({id:7,order: "pillage+",special: true, houseName: EnumHouse.TARGARYEN}),
    new Order({id:8,order: "pillage",special: false, houseName: EnumHouse.TARGARYEN}),
    new Order({id:9,order: "pillage",special: false, houseName: EnumHouse.TARGARYEN}),
    new Order({id:10,order: "support+1",special: true, houseName: EnumHouse.TARGARYEN}),
    new Order({id:11,order: "support",special: false, houseName: EnumHouse.TARGARYEN}),
    new Order({id:12,order: "support",special: false, houseName: EnumHouse.TARGARYEN}),
    new Order({id:13,order: "power+",special: true, houseName: EnumHouse.TARGARYEN}),
    new Order({id:14,order: "power",special: false, houseName: EnumHouse.TARGARYEN}),
    new Order({id:15,order: "power",special: false, houseName: EnumHouse.TARGARYEN }),

    new Order({id:1,order: "attack+1",special: true, houseName: EnumHouse.TYLLER}),
    new Order({id:2,order: "attack0",special: false, houseName: EnumHouse.TYLLER}),
    new Order({id:3,order: "attack-1",special: false, houseName: EnumHouse.TYLLER}),
    new Order({id:4,order: "defend+2",special: true, houseName: EnumHouse.TYLLER}),
    new Order({id:5,order: "defend+1",special: false, houseName: EnumHouse.TYLLER }),
    new Order({id:6,order: "defend+1",special: false, houseName: EnumHouse.TYLLER}),
    new Order({id:7,order: "pillage+",special: true, houseName: EnumHouse.TYLLER}),
    new Order({id:8,order: "pillage",special: false, houseName: EnumHouse.TYLLER}),
    new Order({id:9,order: "pillage",special: false, houseName: EnumHouse.TYLLER}),
    new Order({id:10,order: "support+1",special: true, houseName: EnumHouse.TYLLER}),
    new Order({id:11,order: "support",special: false, houseName: EnumHouse.TYLLER}),
    new Order({id:12,order: "support",special: false, houseName: EnumHouse.TYLLER}),
    new Order({id:13,order: "power+",special: true, houseName: EnumHouse.TYLLER}),
    new Order({id:14,order: "power",special: false, houseName: EnumHouse.TYLLER}),
    new Order({id:15,order: "power",special: false, houseName: EnumHouse.TYLLER }),

    new Order({id:1,order: "attack+1",special: true, houseName: EnumHouse.MARTELL}),
    new Order({id:2,order: "attack0",special: false, houseName: EnumHouse.MARTELL}),
    new Order({id:3,order: "attack-1",special: false, houseName: EnumHouse.MARTELL}),
    new Order({id:4,order: "defend+2",special: true, houseName: EnumHouse.MARTELL}),
    new Order({id:5,order: "defend+1",special: false, houseName: EnumHouse.MARTELL }),
    new Order({id:6,order: "defend+1",special: false, houseName: EnumHouse.MARTELL}),
    new Order({id:7,order: "pillage+",special: true, houseName: EnumHouse.MARTELL}),
    new Order({id:8,order: "pillage",special: false, houseName: EnumHouse.MARTELL}),
    new Order({id:9,order: "pillage",special: false, houseName: EnumHouse.MARTELL}),
    new Order({id:10,order: "support+1",special: true, houseName: EnumHouse.MARTELL}),
    new Order({id:11,order: "support",special: false, houseName: EnumHouse.MARTELL}),
    new Order({id:12,order: "support",special: false, houseName: EnumHouse.MARTELL  }),
    new Order({id:13,order: "power+",special: true, houseName: EnumHouse.MARTELL}),
    new Order({id:14,order: "power",special: false, houseName: EnumHouse.MARTELL}),
    new Order({id:15,order: "power",special: false, houseName: EnumHouse.MARTELL }),

    new Order({id:1,order: "attack+1",special: true, houseName: EnumHouse.STARK}),
    new Order({id:2,order: "attack0",special: false, houseName: EnumHouse.STARK}),
    new Order({id:3,order: "attack-1",special: false, houseName: EnumHouse.STARK}),
    new Order({id:4,order: "defend+2",special: true, houseName: EnumHouse.STARK}),
    new Order({id:5,order: "defend+1",special: false, houseName: EnumHouse.STARK }),
    new Order({id:6,order: "defend+1",special: false, houseName: EnumHouse.STARK}),
    new Order({id:7,order: "pillage+",special: true, houseName: EnumHouse.STARK}),
    new Order({id:8,order: "pillage",special: false, houseName: EnumHouse.STARK}),
    new Order({id:9,order: "pillage",special: false, houseName: EnumHouse.STARK}),
    new Order({id:10,order: "support+1",special: true, houseName: EnumHouse.STARK}),
    new Order({id:11,order: "support",special: false, houseName: EnumHouse.STARK}),
    new Order({id:12,order: "support",special: false, houseName: EnumHouse.STARK}),
    new Order({id:13,order: "power+",special: true, houseName: EnumHouse.STARK}),
    new Order({id:14,order: "power",special: false, houseName: EnumHouse.STARK}),
    new Order({id:15,order: "power",special: false, houseName: EnumHouse.STARK }),

    new Order({id:1,order: "attack+1",special: true, houseName: EnumHouse.GREYJOY}),
    new Order({id:2,order: "attack0",special: false, houseName: EnumHouse.GREYJOY}),
    new Order({id:3,order: "attack-1",special: false, houseName: EnumHouse.GREYJOY}),
    new Order({id:4,order: "defend+2",special: true, houseName: EnumHouse.GREYJOY}),
    new Order({id:5,order: "defend+1",special: false, houseName: EnumHouse.GREYJOY }),
    new Order({id:6,order: "defend+1",special: false, houseName: EnumHouse.GREYJOY}),
    new Order({id:7,order: "pillage+",special: true, houseName: EnumHouse.GREYJOY}),
    new Order({id:8,order: "pillage",special: false, houseName: EnumHouse.GREYJOY}),
    new Order({id:9,order: "pillage",special: false, houseName: EnumHouse.GREYJOY}),
    new Order({id:10,order: "support+1",special: true, houseName: EnumHouse.GREYJOY}),
    new Order({id:11,order: "support",special: false, houseName: EnumHouse.GREYJOY}),
    new Order({id:12,order: "support",special: false, houseName: EnumHouse.GREYJOY}),
    new Order({id:13,order: "power+",special: true, houseName: EnumHouse.GREYJOY}),
    new Order({id:14,order: "power",special: false, houseName: EnumHouse.GREYJOY}),
    new Order({id:15,order: "power",special: false, houseName: EnumHouse.GREYJOY }),
    
]
